# IMPORTANT: This file is generated by cucumber-rails - edit at your own peril.
# It is recommended to regenerate this file in the future when you upgrade to a
# newer version of cucumber-rails. Consider adding your own code to a new file
# instead of editing this one. Cucumber will automatically load all features/**/*.rb
# files.


unless ARGV.any? {|a| a =~ /^gems/} # Don't load anything when running the gems:* tasks

vendored_cucumber_bin = Dir["#{Rails.root}/vendor/{gems,plugins}/cucumber*/bin/cucumber"].first
$LOAD_PATH.unshift(File.dirname(vendored_cucumber_bin) + '/../lib') unless vendored_cucumber_bin.nil?

begin
  require 'cucumber/rake/task'

  namespace :cucumber do
    Cucumber::Rake::Task.new({:ok => 'test:prepare'}, 'Run features that should pass') do |t|
      t.binary = vendored_cucumber_bin # If nil, the gem's binary is used.
      t.fork = true # You may get faster startup if you set this to false
      t.profile = 'default'
    end

    Cucumber::Rake::Task.new({:wip => 'test:prepare'}, 'Run features that are being worked on') do |t|
      t.binary = vendored_cucumber_bin
      t.fork = true # You may get faster startup if you set this to false
      t.profile = 'wip'
    end

    Cucumber::Rake::Task.new({:rerun => 'test:prepare'}, 'Record failing features and run only them if any exist') do |t|
      t.binary = vendored_cucumber_bin
      t.fork = true # You may get faster startup if you set this to false
      t.profile = 'rerun'
    end

    desc 'Run all features'
    task :all => [:ok, :wip]

    task :statsetup do
      require 'rails/code_statistics'
      ::STATS_DIRECTORIES << %w(Cucumber\ features features) if File.exist?('features')
      ::CodeStatistics::TEST_TYPES << "Cucumber features" if File.exist?('features')
    end

    task :annotations_setup do
      Rails.application.configure do
        if config.respond_to?(:annotations)
          config.annotations.directories << 'features'
          config.annotations.register_extensions('feature') { |tag| /#\s*(#{tag}):?\s*(.*)$/ }
        end
      end
    end
  end
  desc 'Alias for cucumber:ok'
  task :cucumber => 'cucumber:ok'

  task :default => :cucumber

  task :features => :cucumber do
    STDERR.puts "*** The 'features' task is deprecated. See rake -T cucumber ***"
  end

  # In case we don't have the generic Rails test:prepare hook, append a no-op task that we can depend upon.
  task 'test:prepare' do
  end

  task :stats => 'cucumber:statsetup'

  task :notes => 'cucumber:annotations_setup'
rescue LoadError
  desc 'cucumber rake task not available (cucumber not installed)'
  task :cucumber do
    abort 'Cucumber rake task is not available. Be sure to install cucumber as a gem or plugin'
  end
end

end

namespace :cucumber do
  desc "Remove all test organisations created by cucumber"
  task :clean_test_organisations => [:environment] do |task|
    Cleaner.new.load_env.clean
  end

  class Cleaner
    def initialize
      self.delay = 2.hours
      self.dry_run = false
    end

    attr_accessor :delay, :dry_run, :keep_count

    def load_env
      self.delay = env('DELAY').hours if env('DELAY')
      self.keep_count = env('KEEP_COUNT')&.to_i
      self.dry_run = (env('DRY_RUN') == "true")

      self
    end

    def env(name)
      ENV["CHOUETTE_CLEAN_TEST_ORGANISATIONS_#{name}"]
    end

    def organisations
      organisations =
        Organisation.joins(:users).
          where("users.email like 'test+%@chouette.test'").distinct

      if delay
        organisations = organisations.where("organisations.created_at < ?", Time.zone.now - delay)
      end

      if keep_count
        organisations = organisations.offset(keep_count)
      end

      organisations
    end

    def clean
      puts "Remove #{organisations.count} test organisation(s)"

      organisations.find_each do |organisation|
        unless dry_run
          Organisation.transaction do
            organisation.workgroups.owned.each(&:destroy!)
            organisation.destroy!
          end
        else
          puts "Destroy Organisation '#{organisation.name}' ##{organisation.id}"
        end
      end
    end
  end
end
