---
definitions:
  services:
    docker:
      memory: 512
    docker-medium:
      memory: 4096
      type: docker
    docker-large:
      memory: 15360
      type: docker
    postgres:
      image:
        name: us-east1-docker.pkg.dev/enroute-interne/enroute-interne/enroute-postgresql:dev
        username: _json_key
        password: "$GCLOUD_API_KEYFILE"
      environment:
        POSTGRES_DB: chouette
        POSTGRES_USER: chouette
        POSTGRES_PASSWORD: chouette
      memory: 2048
    datadog-agent:
      image:
        name: datadog/agent:latest
      environment:
        DD_INSIDE_CI: 'true'
        DD_HOSTNAME: 'none'
        DD_API_KEY: $DATADOG_KEY
  caches:
    bundler: ./vendor/bundle
    yarn: ./node_modules
    assets: ./public/assets
    assets-cache: ./tmp/cache/assets
    build-cache: ./cache
    codacy-coverage: ./.codacy-coverage
  steps:
    - step: &setup
        name: Setup
        image:
          name: us-east1-docker.pkg.dev/enroute-interne/enroute-interne/enroute-ruby:3.4-dev
          username: _json_key
          password: "$GCLOUD_API_KEYFILE"
        caches:
          - bundler
          - yarn
        script:
          - eval "$(build.sh bitbucket::env)"
          - build.sh ci::setup
          - bundle config
        artifacts:
          - node_modules/**
          - vendor/bundle/**
          - .bundle/*

    - step: &build-assets
        name: Build assets
        image:
          name: us-east1-docker.pkg.dev/enroute-interne/enroute-interne/enroute-ruby:3.4-dev
          username: _json_key
          password: "$GCLOUD_API_KEYFILE"
        runs-on:
          - self.hosted
          - build
        caches:
          - assets
          - assets-cache
        script:
          - eval "$(build.sh bitbucket::env)"
          - build.sh bundler::dependencies
          - export RAILS_DB_ADAPTER=nulldb
          - bundle exec rake ci:assets
        artifacts:
          - public/packs-test/**
          - public/assets/**
          - app/packs/src/i18n/translations.json

    - step: &rspec-tests
        name: Ruby Unit tests
        image:
          name: us-east1-docker.pkg.dev/enroute-interne/enroute-interne/enroute-ruby:3.4-dev
          username: _json_key
          password: "$GCLOUD_API_KEYFILE"
        size: 4x
        runs-on:
          - self.hosted
          - build
        max-time: 30
        script:
          - RUNNER_UUID=$(echo "${BITBUCKET_SSH_KEY_FILE}" | sed 's@/var/lib/runner/\(.*\)/ssh/id_rsa@\1@')
          - RAW_BITBUCKET_STEP_UUID=$(echo "${BITBUCKET_STEP_UUID}" | sed -e 's/{//' -e 's/}//')
          - DOCKER_CONTAINER_NAME="${RUNNER_UUID}_${RAW_BITBUCKET_STEP_UUID}_build"

          - docker -H tcp://172.17.0.1 update --cpu-quota=-1 ${DOCKER_CONTAINER_NAME}
          - docker -H tcp://172.17.0.1 inspect ${DOCKER_CONTAINER_NAME}
          - export PARALLEL_TEST_PROCESSORS=9

          - eval "$(build.sh bitbucket::env)"
          - build.sh bundler::dependencies
          - sh -c "[ -f 'cache/runtime.log' ] && sed -i -n '/^spec/ p' cache/runtime.log || true"
          - echo -n $GCLOUD_API_KEYFILE | docker login -u _json_key --password-stdin us-east1-docker.pkg.dev

          - docker run -e POSTGRES_PASSWORD=dummy -v /opt/atlassian/pipelines/agent/build/postgresql:/var/run/postgresql -d us-east1-docker.pkg.dev/enroute-interne/enroute-interne/enroute-postgresql:dev -c effective_cache_size=8092MB -c max_wal_size=20GB -c max_locks_per_transaction=2048

          - export RAILS_TEST_DB_HOST=/opt/atlassian/pipelines/agent/build/postgresql RAILS_DB_USER=postgres RAILS_DB_PASSWORD=
          - sleep 15

          - bundle exec rake ci:setup ci:spec
          - build.sh codacy::report

          - grep ^spec/ parallel_tests/runtime*.log > cache/runtime.log
        caches:
          - build-cache
        artifacts:
          - parallel_tests/*
        services:
          - docker-medium
          - datadog-agent

    - step: &rspec-tests-1
        name: Ruby Unit tests
        image:
          name: us-east1-docker.pkg.dev/enroute-interne/enroute-interne/enroute-ruby:3.4-dev
          username: _json_key
          password: "$GCLOUD_API_KEYFILE"
        size: 4x
        runs-on:
          - self.hosted
          - build
        max-time: 30
        script:
          - eval "$(build.sh bitbucket::env)"
          - build.sh bundler::dependencies
          - BITBUCKET_PARALLEL_STEP_COUNT=4 BITBUCKET_PARALLEL_STEP=0 FAIL_FAST=true bundle exec rake ci:setup ci:spec
          - build.sh codacy::report::partial
        caches:
          - build-cache
        artifacts:
          - parallel_tests/*
        services:
          - postgres
          - datadog-agent

    - step: &rspec-tests-2
        name: Ruby Unit tests
        image:
          name: us-east1-docker.pkg.dev/enroute-interne/enroute-interne/enroute-ruby:3.4-dev
          username: _json_key
          password: "$GCLOUD_API_KEYFILE"
        size: 4x
        runs-on:
          - self.hosted
          - build
        max-time: 30
        script:
          - eval "$(build.sh bitbucket::env)"
          - build.sh bundler::dependencies
          - BITBUCKET_PARALLEL_STEP_COUNT=4 BITBUCKET_PARALLEL_STEP=1 FAIL_FAST=true bundle exec rake ci:setup ci:spec
          - build.sh codacy::report::partial
        caches:
          - build-cache
        artifacts:
          - parallel_tests/*
        services:
          - postgres
          - datadog-agent

    - step: &rspec-tests-3
        name: Ruby Unit tests
        image:
          name: us-east1-docker.pkg.dev/enroute-interne/enroute-interne/enroute-ruby:3.4-dev
          username: _json_key
          password: "$GCLOUD_API_KEYFILE"
        size: 4x
        runs-on:
          - self.hosted
          - build
        max-time: 30
        script:
          - eval "$(build.sh bitbucket::env)"
          - build.sh bundler::dependencies
          - BITBUCKET_PARALLEL_STEP_COUNT=4 BITBUCKET_PARALLEL_STEP=2 FAIL_FAST=true bundle exec rake ci:setup ci:spec
          - build.sh codacy::report::partial
        caches:
          - build-cache
        artifacts:
          - parallel_tests/*
        services:
          - postgres
          - datadog-agent

    - step: &rspec-tests-4
        name: Ruby Unit tests
        image:
          name: us-east1-docker.pkg.dev/enroute-interne/enroute-interne/enroute-ruby:3.4-dev
          username: _json_key
          password: "$GCLOUD_API_KEYFILE"
        size: 4x
        runs-on:
          - self.hosted
          - build
        max-time: 30
        script:
          - eval "$(build.sh bitbucket::env)"
          - build.sh bundler::dependencies
          - BITBUCKET_PARALLEL_STEP_COUNT=4 BITBUCKET_PARALLEL_STEP=3 FAIL_FAST=true bundle exec rake ci:setup ci:spec
          - build.sh codacy::report::partial
        caches:
          - build-cache
        artifacts:
          - parallel_tests/*
        services:
          - postgres
          - datadog-agent

    - step: &rebuild-runtime-log
        name: Rebuild runtime log
        image:
          name: us-east1-docker.pkg.dev/enroute-interne/enroute-interne/enroute-ruby:3.4-dev
          username: _json_key
          password: "$GCLOUD_API_KEYFILE"
        script:
          - grep ^spec/ parallel_tests/runtime*.log > cache/runtime.log
          - build.sh codacy::report::final
        caches:
          - build-cache

    - step: &jest-tests
        name: Javascript Unit tests
        image:
          name: us-east1-docker.pkg.dev/enroute-interne/enroute-interne/enroute-ruby:3.4-dev
          username: _json_key
          password: "$GCLOUD_API_KEYFILE"
        condition:
           state: CHOUETTE_JEST_DISABLED != true
        script:
          - eval "$(build.sh bitbucket::env)"
          - build.sh bundler::dependencies
          - bundle exec rake ci:jest
          - build.sh codacy::report

    - step: &bundle-audit
        name: Bundle Audit
        image:
          name: us-east1-docker.pkg.dev/enroute-interne/enroute-interne/enroute-ruby:3.4-dev
          username: _json_key
          password: "$GCLOUD_API_KEYFILE"
        script:
          - eval "$(build.sh bitbucket::env)"
          - build.sh bundler::dependencies
          - bundle exec rake ci:check_security

    - step: &build-docker
        name: Build Docker
        runs-on:
          - self.hosted
          - build
        size: 4x
        image:
          name: us-east1-docker.pkg.dev/enroute-interne/enroute-interne/enroute-cloud-sdk:latest
          username: _json_key
          password: "$GCLOUD_API_KEYFILE"
        caches:
          - docker
        script:
          - build.sh gcloud::setup
          - DOCKER_BUILD_OPTIONS="--build-arg DEBIAN_PG_API_USERNAME=${DEBIAN_PG_API_USERNAME} --build-arg DEBIAN_PG_API_TOKEN=${DEBIAN_PG_API_TOKEN}" build.sh bitbucket::docker::build
        services:
          - docker-large

pipelines:
  custom:
    gems-update:  # Merge ci-master from chouette-core
      - step:
          name: Update gems
          image:
            name: us-east1-docker.pkg.dev/enroute-interne/enroute-interne/enroute-ruby:3.4-dev
            username: _json_key
            password: "$GCLOUD_API_KEYFILE"
          caches:
            - bundler
            - yarn
            - assets
            - assets-cache
            - build-cache
          script:
            - eval "$(build.sh bitbucket::env)"
            - build.sh ci::setup
            - build.sh bummr::pull-request
          services:
            - postgres

  default:
    - step: *setup
    - step: *build-assets
    - step: *rspec-tests
    - parallel:
        - step: *jest-tests
        - step: *bundle-audit

  branches:
    master:
      - step: *setup
      - step: *build-assets
      - parallel:
          fail-fast: true
          steps:
            - step: *build-docker
            - step: *bundle-audit
            - step: *jest-tests
            - step: *rspec-tests-1
            - step: *rspec-tests-2
            - step: *rspec-tests-3
            - step: *rspec-tests-4
      - step: *rebuild-runtime-log
      - step:
          name: Tag
          artifacts:
            download: false
          script:
            - export TAG_NAME=ci-master
            - git tag -afm "Build ${BITBUCKET_BUILD_NUMBER}" $TAG_NAME
            - git push origin :refs/tags/$TAG_NAME
            - git push origin $TAG_NAME
      - step:
          name: Trigger sub-projects
          artifacts:
            download: false
          script:
            - pipe: atlassian/trigger-pipeline:5.0.1
              variables:
                BITBUCKET_USERNAME: $BITBUCKET_USERNAME
                BITBUCKET_APP_PASSWORD: $BITBUCKET_APP_PASSWORD
                REPOSITORY: $TRIGGER_REPOSITORY_1
                CUSTOM_PIPELINE_NAME: "merge"
            - pipe: atlassian/trigger-pipeline:5.0.1
              variables:
                BITBUCKET_USERNAME: $BITBUCKET_USERNAME
                BITBUCKET_APP_PASSWORD: $BITBUCKET_APP_PASSWORD
                REPOSITORY: $TRIGGER_REPOSITORY_2
                CUSTOM_PIPELINE_NAME: "merge"
      - step:
          name: Deploy to test
          artifacts:
            download: false
          image:
            name: europe-west1-docker.pkg.dev/enroute-interne/enroute-interne/enroute-cloud-sdk:latest
            username: _json_key
            password: "$GCLOUD_API_KEYFILE"
          deployment: test
          runs-on:
            - self.hosted
            - env.interne
            - deploy
          script:
            - git clone git@bitbucket.org:enroute-mobi/chouette-env.git env
            - env/deploy-with-runner.sh
            - pipe: atlassian/datadog-send-event:2.2.0
              variables:
                API_KEY: $DATADOG_KEY
                TITLE: "Build ${BITBUCKET_BUILD_NUMBER} deployed on ${BITBUCKET_REPO_SLUG} ${BITBUCKET_DEPLOYMENT_ENVIRONMENT}"
                PAYLOAD: >
                  { "source_type_name": "BITBUCKET", "tags":["env:test","app:chouette-core","repository:chouette-core"] }

      - step:
          name: Trigger User Tests
          artifacts:
            download: false
          script:
            - pipe: atlassian/trigger-pipeline:5.0.1
              variables:
                BITBUCKET_USERNAME: $BITBUCKET_USERNAME
                BITBUCKET_APP_PASSWORD: $BITBUCKET_APP_PASSWORD
                REPOSITORY: $TRIGGER_REPOSITORY_3
