test:
  service: Disk
  root: <%= Rails.root.join("tmp/storage") %>

file:
  service: Disk
  root: <%= Rails.root.join("storage") %>

gcloud:
  service: GCS
  credentials: <%= SmartEnv['GCLOUD_KEYFILE'] %>
  project: <%= SmartEnv['GCLOUD_PROJECT'] %>
  bucket: <%= SmartEnv['GCLOUD_BUCKET'] %>
