#!/usr/bin/env ruby

ENV['DD_TRACE_CONTEXT'] = ENV['SENTRY_CONTEXT'] = "worker"
require File.expand_path(File.join(File.dirname(__FILE__), '..', 'config', 'environment'))

# Schedule all Cron jobs
Cron::BaseJob.schedule_all

worker_options = {
  :min_priority => ENV['MIN_PRIORITY'],
  :max_priority => ENV['MAX_PRIORITY'],
  :queues => (ENV['QUEUES'] || ENV['QUEUE'] || '').split(','),
  :quiet => ENV['QUIET']
}

worker_options[:sleep_delay] = ENV['SLEEP_DELAY'].to_i if ENV['SLEEP_DELAY']
worker_options[:read_ahead] = ENV['READ_AHEAD'].to_i if ENV['READ_AHEAD']

Delayed::Worker.new(worker_options).start
